services:
  web:
    build: .

    ports:
      - 8000:8000

    environment:
      - MONGO_URL
      - POSTGRES_DSN

    develop:
      watch:
        - path: ./src
          action: sync
          target: /src
          ignore:
            - .venv/

        - path: pyproject.toml
          action: rebuild

        - path: uv.lock
          action: rebuild

    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
